### ISSUE TITLE
Bug erreur SQL adresse show inside input

### ISSUE THREAD

**Issue by Jessy-Charlet** [Jessy-Charlet/Games-Thrones#13]

**Comment by CHAOUCHI** [comment]
Il faudrait ajouter une capture d'écran du bug.

**Comment by Jessy-Charlet** [comment]
![Capture d'écran 2024-04-26 135727](https://github.com/Jessy-Charlet/Games-Thrones/assets/150665196/dd2116f9-4858-40f3-a3e2-f835c2b37ea5)
Warning: Trying to access array offset on value of type bool in C:\laragon\www\GitHub\Games-Thrones\src\profil.php on line 85


Warning: Trying to access array offset on value of type bool in C:\laragon\www\GitHub\Games-Thrones\src\profil.php on line 92


Warning: Trying to access array offset on value of type bool in C:\laragon\www\GitHub\Games-Thrones\src\profil.php on line 97
