### ISSUE TITLE
Valider le paiement dans la page panier Stripe

### ISSUE THREAD

**Issue by Jessy-Charlet** [Jessy-Charlet/Games-Thrones#9]

**Comment by CHAOUCHI** [comment]
Voici la doc de stripe, il faudra créer un back-end avec PHP.
https://docs.stripe.com/api

**Comment by CHAOUCHI** [comment]
Stripe checkout permet de rediriger le client vers le site de stripe pour faire le paiement. Voici la doc (il y a une vidéo d'explication)
https://docs.stripe.com/payments/checkout
